Repository lisbono2001/Covid19-Tracker, pull requests merged in 2020-11, with the labels that each got.

#53 remove tag and last line of index.html
  covid_web/templates/base_template.html
  covid_web/templates/details.html
  covid_web/templates/index.html
Labels: good first issue, refactor

#54 delete unused method
  covid_web/covid_data.py
  covid_web/templates/details.html
Labels: bug fixed, refactor

#57 Need Help! about apply github authentication
  covid_web/covid_data.py
  covid_web/static/images/github_logo.png
  covid_web/static/images/google_login.png
  covid_web/templates/index.html
  mysite/settings.py
  mysite/urls.py
  templates/registration/login.html
Labels: bug fixed, enhancement, help wanted

#61 Merge Unittests branch to master
  .coveragerc
  codecov.yml
  covid_web/covid_data.py
  covid_web/tests.py
  covid_web/tests/__init__.py
  covid_web/tests/test_auth.py
  covid_web/tests/test_details_page.py
  covid_web/tests/test_index.py
  covid_web/views.py
  requirements.txt
  travis.yml
Labels: Code review, enhancement, need comment

#64 fix test for Travis CI
  covid_web/covid_data.py
  covid_web/templates/details.html
  covid_web/tests/test_details_page.py
  covid_web/views.py
Labels: bug fixed, new version

#68 fix fetch data. (due to the changing of API web)
  .coveragerc
  covid_web/templates/index.html
Labels: bug fixed, unittest or ci

#71 Fix covid data fetch not correctly
  covid_web/covid_data.py
Labels: bug fixed, need comment

#72 add Google Slide pf Demo4 to Readme.md
  README.md
Labels: documentation

#70 Modified README and add some git documentation files
  LICENSE.md
  README.md
  contributing.md
Labels: documentation

#73 Add docstrings and apply flake8
  covid_web/covid_data.py
  covid_web/forms.py
  covid_web/tests/__init__.py
  covid_web/tests/test_auth.py
  covid_web/tests/test_details_page.py
  covid_web/tests/test_index.py
  covid_web/views.py
Labels: Code review, refactor

#91 Fix project installation and some documentation
  README.md
  requirements.txt
Labels: documentation

#97 Merge User data to master
  .coveragerc
  .gitignore
  covid_web/covid_data.py
  covid_web/sheets.py
  covid_web/static/covid_web/styles.css
  covid_web/templates/details.html
  covid_web/templates/th_map.html
  covid_web/tests/test_details_page.py
  covid_web/urls.py
  covid_web/views.py
  creds.json
  requirements.txt
  templates/registration/signup.html
Labels: bug fixed, documentation, duplicate, enhancement, new version, refactor

#99 Add Iteration 7 plan in README.md
  README.md
Labels: documentation

#84 Heroku, have to fix more picture on html, and Google login
  covid_web/templates/index.html
  mysite/settings.py
  requirements.txt
Labels: documentation, enhancement, help wanted
